export const CLEAN_STATE = 'CLEAN_STATE'
export const ENGLISH_MOVIES_REQUEST = 'ENGLISH_MOVIES_REQUEST'
export const ENGLISH_MOVIES_SUCCESS = 'ENGLISH_MOVIES_SUCCESS'
export const ENGLISH_MOVIES_FAIL = 'ENGLISH_MOVIES_FAIL'
export const CLEAR_ERRORS = "CLEAR_ERRORS";