export const HINDI_MOVIES_REQUEST = 'HINDI_MOVIES_REQUEST'
export const CLEAN_STATE = 'CLEAN_STATE'
export const HINDI_MOVIES_SUCCESS = 'HINDI_MOVIES_SUCCESS'
export const HINDI_MOVIES_FAIL = 'HINDI_MOVIES_FAIL'
export const CLEAR_ERRORS = "CLEAR_ERRORS";