export const REQUEST_MOVIE_DETAILS='REQUEST_MOVIE_DETAILS'
export const SUCCESS_MOVIE_DETAILS='SUCCESS_MOVIE_DETAILS'
export const FAIL_MOVIE_DETAILS='FAIL_MOVIE_DETAILS'
export const CLEAN_MOVIE_DETAILS='CLEAN_MOVIE_DETAILS'